name: Deploy Lambda Telegram

on:
  push:
    branches: [main]
    paths:
      - 'lambdas/telegram/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Criar pacote ZIP da função Lambda
        run: zip -j lambda.zip lambdas/telegram/main.py

      - name: Deploy para AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          ls -lh
          aws lambda update-function-code \
            --function-name fog-alerts-telegram \
            --zip-file fileb://lambda.zip

      - name: Log de commit
        run: echo "✅ Deploy do commit $GITHUB_SHA feito por $GITHUB_ACTOR"
