name: Deploy Lambda Google Chat

on:
  push:
    branches: [main]
    paths:
      - 'lambdas/google_chat/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Zip Lambda
        run: |
          cd lambdas/google_chat
          zip -r ../lambda.zip main.py

      - name: Deploy via AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          aws lambda update-function-code \
            --function-name fog-alerts-googlechat \
            --zip-file fileb://lambda.zip
      
      - name: Log commit info
        run: echo "Deploying commit $GITHUB_SHA by $GITHUB_ACTOR"

